version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  oms:
    build:
      context: ./OMS
      dockerfile: Dockerfile
    ports:
      - "3003:8080"
    depends_on:
      - kafka
      - mongodb

  pmi:
    build:
      context: ./PMI
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    depends_on:
      - kafka
      - mongodb

  checkout:
    build:
      context: ./Checkout
      dockerfile: Dockerfile
    ports:
      - "3002:8080"
    depends_on:
      - kafka
      - mongodb

volumes:
  mongo-data:
